# Generated by Django 6.0.2 on 2026-02-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlygenerationdata',
            name='country_code',
            field=models.CharField(choices=[('ARG', 'ARG'), ('ARM', 'ARM'), ('AUS', 'AUS'), ('AUT', 'AUT'), ('AZE', 'AZE'), ('BEL', 'BEL'), ('BGD', 'BGD'), ('BGR', 'BGR'), ('BIH', 'BIH'), ('BLR', 'BLR'), ('BOL', 'BOL'), ('BRA', 'BRA'), ('CAN', 'CAN'), ('CHE', 'CHE'), ('CHL', 'CHL'), ('CHN', 'CHN'), ('COL', 'COL'), ('CRI', 'CRI'), ('CYP', 'CYP'), ('CZE', 'CZE'), ('DEU', 'DEU'), ('DNK', 'DNK'), ('DOM', 'DOM'), ('ECU', 'ECU'), ('EGY', 'EGY'), ('ESP', 'ESP'), ('EST', 'EST'), ('FIN', 'FIN'), ('FRA', 'FRA'), ('GBR', 'GBR'), ('GEO', 'GEO'), ('GRC', 'GRC'), ('HRV', 'HRV'), ('HUN', 'HUN'), ('IND', 'IND'), ('IRL', 'IRL'), ('IRN', 'IRN'), ('ITA', 'ITA'), ('JPN', 'JPN'), ('KAZ', 'KAZ'), ('KEN', 'KEN'), ('KGZ', 'KGZ'), ('KOR', 'KOR'), ('KWT', 'KWT'), ('LKA', 'LKA'), ('LTU', 'LTU'), ('LUX', 'LUX'), ('LVA', 'LVA'), ('MAR', 'MAR'), ('MDA', 'MDA'), ('MEX', 'MEX'), ('MKD', 'MKD'), ('MLT', 'MLT'), ('MMR', 'MMR'), ('MNE', 'MNE'), ('MNG', 'MNG'), ('MYS', 'MYS'), ('NGA', 'NGA'), ('NLD', 'NLD'), ('NOR', 'NOR'), ('NZL', 'NZL'), ('OMN', 'OMN'), ('PAK', 'PAK'), ('PER', 'PER'), ('PHL', 'PHL'), ('POL', 'POL'), ('PRI', 'PRI'), ('PRT', 'PRT'), ('QAT', 'QAT'), ('ROU', 'ROU'), ('RUS', 'RUS'), ('SGP', 'SGP'), ('SLV', 'SLV'), ('SRB', 'SRB'), ('SVK', 'SVK'), ('SVN', 'SVN'), ('SWE', 'SWE'), ('THA', 'THA'), ('TJK', 'TJK'), ('TUN', 'TUN'), ('TUR', 'TUR'), ('TWN', 'TWN'), ('UKR', 'UKR'), ('URY', 'URY'), ('USA', 'USA'), ('VNM', 'VNM'), ('XKX', 'XKX'), ('ZAF', 'ZAF')], max_length=3),
        ),
    ]
