# Generated by Django 6.0.2 on 2026-02-24 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_countryfuel_generation_latest_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryFuelYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('is_complete', models.BooleanField(help_text='Indicates if we have data for the entire year.')),
                ('share', models.FloatField(help_text="Share of this country's total fuel generation that came from this fuel")),
                ('generation', models.FloatField(help_text='Total electricity generation from this fuel for this year and country')),
                ('yoy_growth', models.FloatField(help_text='Percent growth since the previous year. A value of zero is used if no data are available for the previous year.')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_data', to='core.country')),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_data', to='core.fuel')),
            ],
            options={
                'unique_together': {('country', 'fuel', 'year')},
            },
        ),
    ]
