# Generated by Django 6.0.2 on 2026-03-04 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_fuelyear"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyGenerationRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(help_text="Month for which this record applies (first day of the month)")),
                (
                    "record_type",
                    models.CharField(help_text="Type of record, e.g. 'generation' or 'share'", max_length=32),
                ),
                (
                    "generation_twh",
                    models.FloatField(
                        help_text="Electricity generation from this fuel in this month (TWh) at the time of the record"
                    ),
                ),
                (
                    "share_of_generation_pct",
                    models.FloatField(
                        help_text="Share of total generation from this fuel in this month (%) at the time of the record"
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        help_text="Country for which this record was set",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_generation_records",
                        to="core.country",
                    ),
                ),
                (
                    "fuel",
                    models.ForeignKey(
                        help_text="Fuel type for which this record was set",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_generation_records",
                        to="core.fuel",
                    ),
                ),
            ],
            options={
                "verbose_name": "monthly generation record",
                "verbose_name_plural": "monthly generation records",
                "ordering": ["country", "fuel", "date", "record_type"],
            },
        ),
    ]
