# Generated by Django 6.0.2 on 2026-03-23 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_monthlygenerationrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountryEnergyBalanceYear",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.IntegerField(help_text="Calendar year")),
                (
                    "coal_supply",
                    models.IntegerField(help_text="Total energy supply from coal, peat and oil shale (PJ)"),
                ),
                (
                    "oil_supply",
                    models.IntegerField(help_text="Total energy supply from crude oil, NGL and feedstocks (PJ)"),
                ),
                ("gas_supply", models.IntegerField(help_text="Total energy supply from natural gas (PJ)")),
                ("nuclear_supply", models.IntegerField(help_text="Total energy supply from nuclear (PJ)")),
                (
                    "renewable_supply",
                    models.IntegerField(help_text="Total energy supply from renewables and waste (PJ)"),
                ),
                (
                    "total_supply",
                    models.IntegerField(help_text="Sum of coal, oil, gas, nuclear and renewable supply (PJ)"),
                ),
                (
                    "share_low_carbon",
                    models.FloatField(
                        help_text="Percentage share of total energy supply from nuclear and renewable sources"
                    ),
                ),
                (
                    "share_renewable",
                    models.FloatField(help_text="Percentage share of total energy supply from renewable sources"),
                ),
                (
                    "share_electricity",
                    models.FloatField(help_text="Total electricity production as a percentage of total energy supply"),
                ),
                (
                    "country",
                    models.ForeignKey(
                        help_text="Country this balance applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="energy_balance_years",
                        to="core.country",
                    ),
                ),
            ],
            options={
                "verbose_name": "country energy balance year",
                "verbose_name_plural": "country energy balance years",
                "ordering": ["country", "year"],
                "unique_together": {("country", "year")},
            },
        ),
    ]
