# Generated by Django 6.0.2 on 2026-04-07 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_country_energy_balance_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountryTrackerYear",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.IntegerField(help_text="Calendar year")),
                ("electricity_rank", models.IntegerField(help_text="The country's rank as an electricity producer")),
                (
                    "electricity_share_low_carbon",
                    models.FloatField(help_text="Share of electricity generation from low-carbon sources (%)"),
                ),
                (
                    "share_electricity",
                    models.FloatField(help_text="Share of primary energy that is generating electricity (%)"),
                ),
                (
                    "energy_share_low_carbon",
                    models.FloatField(help_text="Share of primary energy from low-carbon sources (%)"),
                ),
                (
                    "country",
                    models.ForeignKey(
                        help_text="Country this tracker row applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracker_years",
                        to="core.country",
                    ),
                ),
            ],
            options={
                "verbose_name": "country tracker year",
                "verbose_name_plural": "country tracker years",
                "ordering": ["country", "year"],
                "unique_together": {("country", "year")},
            },
        ),
    ]
