# Generated by Django 6.0.2 on 2026-04-07 19:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_countrytrackeryear"),
    ]

    operations = [
        migrations.RenameField(
            model_name="country",
            old_name="low_carbon_pct",
            new_name="share_low_carbon",
        ),
    ]
