# Generated by Django 6.0.2 on 2026-04-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_remove_country_low_carbon_pct_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="countrytrackeryear",
            name="generation_twh",
            field=models.FloatField(
                blank=True, help_text="Total electricity generation for this country and year (TWh)", null=True
            ),
        ),
    ]
