# Generated by Django 6.0.2 on 2026-04-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_countrytrackeryear_generation_twh_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="share_low_carbon",
            field=models.FloatField(
                blank=True,
                help_text="Share of this country's electricity generation from low-carbon sources (%)",
                null=True,
            ),
        ),
    ]
