# Generated by Django 6.0.2 on 2026-04-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_country_share_low_carbon'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Calendar year', unique=True)),
                ('generation_twh', models.FloatField(blank=True, help_text='Total electricity generation across all countries for this year (TWh)', null=True)),
                ('electricity_share_low_carbon', models.FloatField(help_text='Share of electricity generation from low-carbon sources (%)')),
                ('share_electricity', models.FloatField(help_text='Share of primary energy that is generating electricity (%)')),
                ('energy_share_low_carbon', models.FloatField(help_text='Share of primary energy from low-carbon sources (%)')),
            ],
            options={
                'verbose_name': 'tracker year',
                'verbose_name_plural': 'tracker years',
                'ordering': ['year'],
            },
        ),
    ]
