# Generated by Django 6.0.2 on 2026-05-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_fuelmonth'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelmonth',
            name='country_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of distinct countries with data for this fuel in this month'),
        ),
    ]
