# Generated by Django 6.0.2 on 2026-10-02 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_fuelmonth_country_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenerationUnit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "region",
                    models.CharField(
                        help_text="Subnational region (e.g. province or state) where this unit is located",
                        max_length=100,
                    ),
                ),
                ("year", models.IntegerField(help_text="Calendar year this capacity snapshot applies to")),
                ("generation_unit_name", models.CharField(help_text="Name of the generation unit", max_length=200)),
                (
                    "unit_effective_capacity_mw",
                    models.FloatField(help_text="Effective capacity of this generation unit (MW)"),
                ),
                (
                    "unit_average_annual_energy_gwh",
                    models.FloatField(help_text="Average annual energy produced by this generation unit (GWh)"),
                ),
                (
                    "country",
                    models.ForeignKey(
                        help_text="Country where this generation unit is located",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_units",
                        to="core.country",
                    ),
                ),
                (
                    "fuel",
                    models.ForeignKey(
                        help_text="Fuel / technology type for this generation unit",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_units",
                        to="core.fuel",
                    ),
                ),
            ],
            options={
                "verbose_name": "generation unit",
                "verbose_name_plural": "generation units",
                "ordering": ["country", "region", "generation_unit_name"],
            },
        ),
    ]
