# Generated by Django 6.0.2 on 2026-10-02 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_generationunit"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenerationUnitRegionFuelYear",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "region",
                    models.CharField(
                        help_text="Subnational region (e.g. province or state) these generation units belong to",
                        max_length=100,
                    ),
                ),
                ("year", models.IntegerField(help_text="Calendar year this capacity snapshot applies to")),
                (
                    "effective_capacity_mw",
                    models.FloatField(
                        help_text="Sum of effective capacity across generation units in this region/fuel/year (MW)"
                    ),
                ),
                (
                    "average_annual_energy_gwh",
                    models.FloatField(
                        help_text="Sum of average annual energy across generation units in this region/fuel/year (GWh)"
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        help_text="Country these generation units belong to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_unit_region_fuel_years",
                        to="core.country",
                    ),
                ),
                (
                    "fuel",
                    models.ForeignKey(
                        help_text="Fuel / technology type for these generation units",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_unit_region_fuel_years",
                        to="core.fuel",
                    ),
                ),
            ],
            options={
                "verbose_name": "generation unit region fuel year",
                "verbose_name_plural": "generation unit region fuel years",
                "ordering": ["country", "region", "fuel", "year"],
                "unique_together": {("country", "region", "fuel", "year")},
            },
        ),
    ]
